on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: rust
      - name: Update Helm chart version
        run: |
          VERSION=$(cat version.txt)
          yq eval -i ".version = \"$VERSION\"" charts/Chart.yaml
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: release $VERSION"
          git push
