apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simulation-operator
rules:
- apiGroups: ["rumsim.io"]
  resources: ["simulations"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["patch", "create", "delete", "get", "list", "update"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["patch", "create", "delete", "get", "list", "update"]
