apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "rumsimop.fullname" . }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ include "rumsimop.name" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "rumsimop.name" . }}"
    spec:
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecrets }}"
      containers:
        - name: rumsimop
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: BROKER_URL
              value: "{{ .Values.broker.url }}"
            - name: BROKER_USER
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: BROKER_USER
            - name: BROKER_PASS
              valueFrom:
                secretKeyRef:
                  name: broker-secret
                  key: BROKER_PASS
            - name: OTLP_COLLECTOR
              value: "{{ .Values.otlp.collector }}"
            - name: OTLP_AUTH
              value: "{{ .Values.otlp.auth }}"
