apiVersion: v1
kind: Secret
metadata:
  name: broker-secret
type: Opaque
data:
  # prettier-ignore
  BROKER_USER: {{ .Values.broker.user | b64enc | quote }}
  BROKER_PASS: {{ .Values.broker.pass | b64enc | quote }}
