name: Update Helm chart version on release please PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-chart-version:
    if: startsWith(github.event.pull_request.title, 'chore(main)')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.head_ref }}
      - name: Update Helm chart version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | head -1 | awk -F'"' '{print $2}')
          yq eval -i ".version = \"$VERSION\"" charts/Chart.yaml
      - uses: stefanzweifel/git-auto-commit-action@v5
