name: Helm

on:
  push:
    branches: ["main"]
    paths:
      - "charts/**"
  pull_request:
    branches: ["main"]
    paths:
      - "charts/**"
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Helm
        uses: Azure/setup-helm@v4

      - name: Package Helm chart
        run: |
          helm package charts --destination . # --version ${{ github.ref }}

      - name: Checkout "charts" repository
        uses: actions/checkout@v4.1.1
        with:
          repository: eickler/charts
          token: ${{ secrets.CHARTS_TOKEN }}
          path: charts-repo

      - name: Copy Helm chart to "charts" repository
        run: |
          cp *.tgz charts-repo/

      - name: Update Helm repo index
        run: |
          cd charts-repo
          helm repo index .

      - name: Push changes
        run: |
          cd charts-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Helm chart"
          git push
