name: Release pull request maintenance

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.PR_TOKEN }}
          release-type: rust
